version: "3.8"

services: 
################################################       
#######PHP7.1-FPM 
    php7.1-fpm:
        image: ${DOCKER_USER}/php-fpm:7.1
        build:
          context: ./php-fpm
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=7.1
#######PHP7.2-FPM 
    php7.2-fpm:
        image: ${DOCKER_USER}/php-fpm:7.2
        build:
          context: ./php-fpm
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=7.2          
#######PHP7.3-FPM  
    php7.3-fpm:
        image: ${DOCKER_USER}/php-fpm:7.3
        build:
          context: ./php-fpm
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=7.3
#######PHP7.4-FPM    
    php7.4-fpm:
        image: ${DOCKER_USER}/php-fpm:7.4
        build:
          context: ./php-fpm
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=7.4
    php7.4-fpm-bullseye:
        image: ${DOCKER_USER}/php-fpm:7.4-bullseye
        build:
          context: ./php-fpm
          args:
            - X_PHP_VERSION=7.4
            - X_DEBIAN_RELEASE=bullseye
            - CHANGE_SOURCE=true
#######PHP8.2-FPM    
    php8.2-fpm:
        image: ${DOCKER_USER}/php-fpm:8.2
        build:
          context: ./php-fpm
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=8.2             
### PHP-CLI ########################################  
#######PHP7.1-CLI
    php7.1-cli:
        image: ${DOCKER_USER}/php-cli:7.1
        build:
          context: ./php-cli
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=7.1

#######PHP7.4-CLI
    php7.4-cli:
        image: ${DOCKER_USER}/php-cli:7.4
        build:
          context: ./php-cli
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=7.4

#######PHP8.2-CLI
    php8.2-cli:
        image: ${DOCKER_USER}/php-cli:8.2
        build:
          context: ./php-cli
          args:
            - CHANGE_SOURCE=true
            - X_PHP_VERSION=8.2